# Generated by Django 2.2 on 2019-04-10 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchlist_name', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=250)),
                ('movie_premiere_year', models.IntegerField(verbose_name='premiere year')),
                ('movie_score', models.FloatField(verbose_name='score')),
                ('movie_genres', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('watchlist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.WatchList')),
            ],
        ),
    ]
