# Generated by Django 2.2 on 2019-04-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='movie_genres',
            field=models.CharField(max_length=250),
        ),
    ]
